all:
  hosts:
    dns01.lab.skog.network:
      ansible_host: 10.0.29.12
    dhcp01.lab.skog.network:
      ansible_host: 10.0.29.254
    podman01.lab.skog.network:
      ansible_host: 10.0.22.51
    db01.lab.skog.network:
      ansible_host: 10.0.22.52   


    master01.lab.skog.network:
      ansible_host: 10.0.23.223
    master02.lab.skog.network:
      ansible_host: 10.0.23.200
    master03.lab.skog.network:
      ansible_host: 10.0.23.105
    worker01.lab.skog.network:
      ansible_host: 10.0.23.191
    worker02.lab.skog.network:
      ansible_host: 10.0.23.142
    worker03.lab.skog.network:
      ansible_host: 10.0.23.217
    worker04.lab.skog.network:
      ansible_host: 10.0.23.235
    worker05.lab.skog.network:
      ansible_host: 10.0.23.196
    worker06.lab.skog.network:
      ansible_host: 10.0.23.202
  children:
    dns:
      hosts:
        dns01.lab.skog.network:
    dhcp:
      hosts:
        dhcp01.lab.skog.network:
    podman:
      hosts:
        podman01.lab.skog.network:
    databases:
      hosts:
        db01.lab.skog.network:
        
    
    kubernetes_masters:
      hosts:
        master01.lab.skog.network:
        master02.lab.skog.network:
        master03.lab.skog.network:
    kubernetes_workers:
      hosts:
        worker01.lab.skog.network:
        worker02.lab.skog.network:
        worker03.lab.skog.network:
        worker04.lab.skog.network:
        worker05.lab.skog.network:
        worker06.lab.skog.network:
    kubernetes:
      children:
        kubernetes_masters:
        kubernetes_workers:
