all:
  hosts:
    dns01.lab.skog.network:
      ansible_host: 10.0.29.12
    dhcp01.lab.skog.network:
      ansible_host: 10.0.29.254
    podman01.lab.skog.network:
      ansible_host: 10.0.22.51
    db01.lab.skog.network:
      ansible_host: 10.0.22.52   

    k1-m1.lab.skog.network:
      ansible_host: 10.0.23.246
    k1-m2.lab.skog.network:
      ansible_host: 10.0.23.134
    k1-m3.lab.skog.network:
      ansible_host: 10.0.23.240
    k1-w1.lab.skog.network:
      ansible_host: 10.0.23.160
    k1-w2.lab.skog.network:
      ansible_host: 10.0.23.103
    k1-w3.lab.skog.network:
      ansible_host: 10.0.23.102
    k1-w4.lab.skog.network:
      ansible_host: 10.0.23.101
    k1-w5.lab.skog.network:
      ansible_host: 10.0.23.215
    k1-w6.lab.skog.network:
      ansible_host: 10.0.23.104
    k1-w7.lab.skog.network:
      ansible_host: 10.0.23.155
    k1-w8.lab.skog.network:
      ansible_host: 10.0.23.231
    k1-w9.lab.skog.network:
      ansible_host: 10.0.23.213

  children:
    dns:
      hosts:
        dns01.lab.skog.network:
    dhcp:
      hosts:
        dhcp01.lab.skog.network:
    podman:
      hosts:
        podman01.lab.skog.network:
    databases:
      hosts:
        db01.lab.skog.network:
        
    
    kubernetes_masters:
      hosts:
        k1-m1.lab.skog.network:
        #k1-m2.lab.skog.network:
        #k1-m3.lab.skog.network:
    kubernetes_workers:
      hosts:
        k1-w1.lab.skog.network:
        k1-w2.lab.skog.network:
        k1-w3.lab.skog.network:
        k1-w4.lab.skog.network:
        k1-w5.lab.skog.network:
        k1-w6.lab.skog.network:
        k1-w7.lab.skog.network:
        k1-w8.lab.skog.network:
        k1-w9.lab.skog.network:
    kubernetes:
      children:
        kubernetes_masters:
        kubernetes_workers:
