#SPDX-License-Identifier: MIT-0
---
# handlers file for kubernetes_masters
- name: Change kubeconfig permissions
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"