---
- name: Detect operating system
  hosts: all
  ansible.builtin.set_fact:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_rhel: "{{ ansible_os_family == 'RedHat' }}"

- name: Install required packages (Debian)
  ansible.builtin.apt:
    name: '*'
    state: latest
  when: is_debian

- name: Install required packages (RHEL)
  ansible.builtin.dnf:
    name: '*'
    state: latest
  when: is_rhel