---
name: ansible-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Run ansible-lint
        uses: ansible/ansible-lint@8ba9595a4acd1b906eb75568b34f6ef592cd1528
        with:
          setup_python: true
          python_version: "3.14"
          working_directory: "ansible"
          requirements_file: "requirements.yml"
